<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>13aa8e57-bd47-4af8-9d62-2f2120ac4a15</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
    <PackageReference Include="AutoMapper" Version="15.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartTripPlanner.Infrastructure\SmartTripPlanner.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartTripPlanner.ApplicationServices\SmartTripPlanner.ApplicationServices.csproj" />
  </ItemGroup>

</Project>
