// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartTripPlanner.Infrastructure;

#nullable disable

namespace SmartTripPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260609190740_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityCode")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("DefaultStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.Trip", b =>
                {
                    b.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.DayPlan", "Days", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<int>("DayIndex")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone");

                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.Property<int>("WeatherSummary")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("TripId");

                            b1.ToTable("DayPlan");

                            b1.WithOwner()
                                .HasForeignKey("TripId");

                            b1.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.BlockTimeline", "Afternoon", b2 =>
                                {
                                    b2.Property<long>("DayPlanId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("BlockTotalDurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<long>("Id")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DayPlanId");

                                    b2.ToTable("DayPlan");

                                    b2.WithOwner()
                                        .HasForeignKey("DayPlanId");

                                    b2.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.ActivityNode", "Activities", b3 =>
                                        {
                                            b3.Property<long>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<long>("Id"));

                                            b3.Property<long>("DayPlanId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("DurationMinutes")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedArrival")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedDeparture")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsCompleted")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("IsIndoor")
                                                .HasColumnType("boolean");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("PlaceId")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<int>("Priority")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer");

                                            b3.HasKey("Id");

                                            b3.HasIndex("DayPlanId");

                                            b3.ToTable("AfternoonActivities", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DayPlanId");

                                            b3.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.TransitDetails", "TransitToNext", b4 =>
                                                {
                                                    b4.Property<long>("ActivityNodeId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<int>("BufferMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("DurationMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<bool>("FrictionAlert")
                                                        .HasColumnType("boolean");

                                                    b4.Property<int>("TransportMode")
                                                        .HasColumnType("integer");

                                                    b4.HasKey("ActivityNodeId");

                                                    b4.ToTable("AfternoonActivities");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ActivityNodeId");
                                                });

                                            b3.Navigation("TransitToNext");
                                        });

                                    b2.Navigation("Activities");
                                });

                            b1.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.BlockTimeline", "Evening", b2 =>
                                {
                                    b2.Property<long>("DayPlanId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("BlockTotalDurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<long>("Id")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DayPlanId");

                                    b2.ToTable("DayPlan");

                                    b2.WithOwner()
                                        .HasForeignKey("DayPlanId");

                                    b2.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.ActivityNode", "Activities", b3 =>
                                        {
                                            b3.Property<long>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<long>("Id"));

                                            b3.Property<long>("DayPlanId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("DurationMinutes")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedArrival")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedDeparture")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsCompleted")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("IsIndoor")
                                                .HasColumnType("boolean");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("PlaceId")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<int>("Priority")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer");

                                            b3.HasKey("Id");

                                            b3.HasIndex("DayPlanId");

                                            b3.ToTable("EveningActivities", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DayPlanId");

                                            b3.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.TransitDetails", "TransitToNext", b4 =>
                                                {
                                                    b4.Property<long>("ActivityNodeId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<int>("BufferMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("DurationMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<bool>("FrictionAlert")
                                                        .HasColumnType("boolean");

                                                    b4.Property<int>("TransportMode")
                                                        .HasColumnType("integer");

                                                    b4.HasKey("ActivityNodeId");

                                                    b4.ToTable("EveningActivities");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ActivityNodeId");
                                                });

                                            b3.Navigation("TransitToNext");
                                        });

                                    b2.Navigation("Activities");
                                });

                            b1.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.BlockTimeline", "Morning", b2 =>
                                {
                                    b2.Property<long>("DayPlanId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("BlockTotalDurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<long>("Id")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DayPlanId");

                                    b2.ToTable("DayPlan");

                                    b2.WithOwner()
                                        .HasForeignKey("DayPlanId");

                                    b2.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.ActivityNode", "Activities", b3 =>
                                        {
                                            b3.Property<long>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<long>("Id"));

                                            b3.Property<long>("DayPlanId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("DurationMinutes")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedArrival")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedDeparture")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsCompleted")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("IsIndoor")
                                                .HasColumnType("boolean");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("PlaceId")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<int>("Priority")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer");

                                            b3.HasKey("Id");

                                            b3.HasIndex("DayPlanId");

                                            b3.ToTable("MorningActivities", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DayPlanId");

                                            b3.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.TransitDetails", "TransitToNext", b4 =>
                                                {
                                                    b4.Property<long>("ActivityNodeId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<int>("BufferMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("DurationMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<bool>("FrictionAlert")
                                                        .HasColumnType("boolean");

                                                    b4.Property<int>("TransportMode")
                                                        .HasColumnType("integer");

                                                    b4.HasKey("ActivityNodeId");

                                                    b4.ToTable("MorningActivities");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ActivityNodeId");
                                                });

                                            b3.Navigation("TransitToNext");
                                        });

                                    b2.Navigation("Activities");
                                });

                            b1.Navigation("Afternoon")
                                .IsRequired();

                            b1.Navigation("Evening")
                                .IsRequired();

                            b1.Navigation("Morning")
                                .IsRequired();
                        });

                    b.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.Location", "BaseHotel", b1 =>
                        {
                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("HotelLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("HotelLongitude");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("HotelName");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.SelectedAttraction", "SelectedAttractions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PlaceId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("TripId");

                            b1.ToTable("SelectedAttraction");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("BaseHotel")
                        .IsRequired();

                    b.Navigation("Days");

                    b.Navigation("SelectedAttractions");
                });
#pragma warning restore 612, 618
        }
    }
}
