// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartTripPlanner.Infrastructure;

#nullable disable

namespace SmartTripPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    partial class PlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CityCode")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CityCode = "madrid",
                            CityName = "Madrid",
                            IsAllowed = true
                        });
                });

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.Place", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAutoUpdateEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFamilyFriendly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsIndoor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TypicalDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ProviderReferenceId")
                        .IsUnique();

                    b.ToTable("Places");
                });

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("DefaultStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("CREATED");

                    b.Property<string>("TripCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripCode")
                        .IsUnique();

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.Place", b =>
                {
                    b.HasOne("SmartTripPlanner.Domain.AggregatesModel.City", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.OpeningHoursWindow", "OpeningHours", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<int>("CloseMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer");

                            b1.Property<int>("OpenMinutes")
                                .HasColumnType("integer");

                            b1.Property<long>("PlaceId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("PlaceId");

                            b1.ToTable("PlaceOpeningHours", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.PlaceAttribute", "Attributes", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<long>("PlaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("PlaceId", "Value");

                            b1.ToTable("PlaceAttributes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.PlaceLocation", "Location", b1 =>
                        {
                            b1.Property<long>("PlaceId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("PlaceId");

                            b1.ToTable("Places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("City");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("OpeningHours");
                });

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.Trip", b =>
                {
                    b.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.DayPlan", "Days", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<int>("DayIndex")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone");

                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.Property<int>("WeatherSummary")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("TripId");

                            b1.ToTable("DayPlan");

                            b1.WithOwner()
                                .HasForeignKey("TripId");

                            b1.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.BlockTimeline", "Afternoon", b2 =>
                                {
                                    b2.Property<long>("DayPlanId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("BlockTotalDurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<long>("Id")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DayPlanId");

                                    b2.ToTable("DayPlan");

                                    b2.WithOwner()
                                        .HasForeignKey("DayPlanId");

                                    b2.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.ActivityNode", "Activities", b3 =>
                                        {
                                            b3.Property<long>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<long>("Id"));

                                            b3.Property<long>("DayPlanId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("DurationMinutes")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedArrival")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedDeparture")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsCompleted")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("IsIndoor")
                                                .HasColumnType("boolean");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("PlaceId")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<int>("Priority")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer");

                                            b3.HasKey("Id");

                                            b3.HasIndex("DayPlanId");

                                            b3.ToTable("AfternoonActivities", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DayPlanId");

                                            b3.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.TransitDetails", "TransitToNext", b4 =>
                                                {
                                                    b4.Property<long>("ActivityNodeId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<int>("BufferMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("DurationMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<bool>("FrictionAlert")
                                                        .HasColumnType("boolean");

                                                    b4.Property<int>("TransportMode")
                                                        .HasColumnType("integer");

                                                    b4.HasKey("ActivityNodeId");

                                                    b4.ToTable("AfternoonActivities");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ActivityNodeId");
                                                });

                                            b3.Navigation("TransitToNext");
                                        });

                                    b2.Navigation("Activities");
                                });

                            b1.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.BlockTimeline", "Evening", b2 =>
                                {
                                    b2.Property<long>("DayPlanId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("BlockTotalDurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<long>("Id")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DayPlanId");

                                    b2.ToTable("DayPlan");

                                    b2.WithOwner()
                                        .HasForeignKey("DayPlanId");

                                    b2.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.ActivityNode", "Activities", b3 =>
                                        {
                                            b3.Property<long>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<long>("Id"));

                                            b3.Property<long>("DayPlanId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("DurationMinutes")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedArrival")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedDeparture")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsCompleted")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("IsIndoor")
                                                .HasColumnType("boolean");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("PlaceId")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<int>("Priority")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer");

                                            b3.HasKey("Id");

                                            b3.HasIndex("DayPlanId");

                                            b3.ToTable("EveningActivities", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DayPlanId");

                                            b3.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.TransitDetails", "TransitToNext", b4 =>
                                                {
                                                    b4.Property<long>("ActivityNodeId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<int>("BufferMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("DurationMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<bool>("FrictionAlert")
                                                        .HasColumnType("boolean");

                                                    b4.Property<int>("TransportMode")
                                                        .HasColumnType("integer");

                                                    b4.HasKey("ActivityNodeId");

                                                    b4.ToTable("EveningActivities");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ActivityNodeId");
                                                });

                                            b3.Navigation("TransitToNext");
                                        });

                                    b2.Navigation("Activities");
                                });

                            b1.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.BlockTimeline", "Morning", b2 =>
                                {
                                    b2.Property<long>("DayPlanId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("BlockTotalDurationMinutes")
                                        .HasColumnType("integer");

                                    b2.Property<long>("Id")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DayPlanId");

                                    b2.ToTable("DayPlan");

                                    b2.WithOwner()
                                        .HasForeignKey("DayPlanId");

                                    b2.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.ActivityNode", "Activities", b3 =>
                                        {
                                            b3.Property<long>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<long>("Id"));

                                            b3.Property<long>("DayPlanId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("DurationMinutes")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedArrival")
                                                .HasColumnType("integer");

                                            b3.Property<int>("EstimatedDeparture")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsCompleted")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("IsIndoor")
                                                .HasColumnType("boolean");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("PlaceId")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<int>("Priority")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer");

                                            b3.HasKey("Id");

                                            b3.HasIndex("DayPlanId");

                                            b3.ToTable("MorningActivities", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DayPlanId");

                                            b3.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.TransitDetails", "TransitToNext", b4 =>
                                                {
                                                    b4.Property<long>("ActivityNodeId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<int>("BufferMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("DurationMinutes")
                                                        .HasColumnType("integer");

                                                    b4.Property<bool>("FrictionAlert")
                                                        .HasColumnType("boolean");

                                                    b4.Property<int>("TransportMode")
                                                        .HasColumnType("integer");

                                                    b4.HasKey("ActivityNodeId");

                                                    b4.ToTable("MorningActivities");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ActivityNodeId");
                                                });

                                            b3.Navigation("TransitToNext");
                                        });

                                    b2.Navigation("Activities");
                                });

                            b1.Navigation("Afternoon")
                                .IsRequired();

                            b1.Navigation("Evening")
                                .IsRequired();

                            b1.Navigation("Morning")
                                .IsRequired();
                        });

                    b.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.Location", "BaseHotel", b1 =>
                        {
                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("HotelLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("HotelLongitude");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("HotelName");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsMany("SmartTripPlanner.Domain.AggregatesModel.MustSee", "OriginalMustSees", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("PinnedBlock")
                                .HasColumnType("text");

                            b1.Property<int?>("PinnedDayIndex")
                                .HasColumnType("integer");

                            b1.Property<long>("PlaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("TripId");

                            b1.ToTable("TripMustSees", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.Travelers", "Travelers", b1 =>
                        {
                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Adults")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(2)
                                .HasColumnName("TravelersAdults");

                            b1.Property<int>("Children")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("TravelersChildren");

                            b1.Property<int>("Infants")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("TravelersInfants");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("SmartTripPlanner.Domain.AggregatesModel.TripPreferences", "Preferences", b1 =>
                        {
                            b1.Property<long>("TripId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("CarAvailable")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("PrefCarAvailable");

                            b1.Property<int>("MaxWalkingMinutes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(30)
                                .HasColumnName("PrefMaxWalkingMinutes");

                            b1.Property<bool>("WeatherAwareEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("PrefWeatherAwareEnabled");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("BaseHotel")
                        .IsRequired();

                    b.Navigation("Days");

                    b.Navigation("OriginalMustSees");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("Travelers")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartTripPlanner.Domain.AggregatesModel.City", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
